version: "2.2"

services:
  kibana:
    image: gitlab.exi.com:9190/kibana:8.10.4
    container_name: kibana
    restart: always
    volumes:
      - ./certs:/usr/share/kibana/config/certs
    ports:
      - "5601:5601"
    environment:
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_HOSTS=["https://192.168.10.101:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt

  logstash:
    image: gitlab.exi.com:9190/logstash:8.10.4
    container_name: logstash
    restart: always
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./certs:/usr/share/logstash/config/certs
    ports:
      - "5044:5044"
    environment:
      - LS_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.monitoring.elasticsearch.hosts=["https://192.168.10.101:9200"]
      - xpack.monitoring.elasticsearch.username=logstash_system
      - xpack.monitoring.elasticsearch.password=${LOGSTASH_PASSWORD}
      - xpack.monitoring.elasticsearch.ssl.certificate_authorities=config/certs/ca/ca.crt

